#hello:
#  path: /helloworld
#  controller: App\Controller\HelloController::hello

controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation
