<div class="container">
  <div class="row justify-content-center">
    <h2 class="text-justify"><?= $articlesdetail['title']?></h2>
  </div>
</div>


<img class="img-thumbnail rounded float-left" src="<?= $articlesdetail['image']; ?>"/>
<p class="text-justify m-5"><?= $articlesdetail['content']; ?></p>

<p>Publier le <?= $articlesdetail['dateArticle']; ?></p>

<button><a href="update.php?numero=<?=$articlesdetail['idArticle']; ?> "> Update <a/></button>


<div>
  <h3>Commentaire</h3>
</div>


<?php foreach($commentaires as $commentaire): ?>


<div class="<col-md-5></col-md-5>">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <h3 class="mb-0">
                <a class="text-dark" href="#"><?= $commentaire["pseudo"]; ?></a>
              </h3>
              <p class="card-text mb-auto"><?= $commentaire["message"]; ?></p>
              <p><?= $commentaire["dateComment"]; ?></p>
            </div>
         </div>
    </div>
    
    <?php endforeach; ?>






<form action="commentaire.php?numero=<?= $num; ?>" method="post" >
  
  <fieldset>
    
    <legend>laisser un commentaire </legend>
    
  <div class="form-group">
    <label for="formGroupExampleInput">Pseudo</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="momo45" name="pseudo">
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">message</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="message"></textarea>
  </div>
 
  <br>
   
   </fieldset>
     <button class="btn btn-info btn-md  ms-1" type="submit" value="submit">Envoyer</button>
 
</form>