<div class="container">
  <div class="row justify-content-center">
    <h2 class="text-justify">Bienvenue sur le blog de idw02</h2>
  </div>
</div>



<?php foreach($articles as $article): ?>


<div class="<col-md-5></col-md-5>">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">World</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="#"><?= $article["title"]; ?></a>
              </h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto"><?= substr($article["content"],0, 100); ?></p>
              <a href="article.php?numero=<?=$article['idArticle']; ?> ">Voir plus <a/>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" style="width: 200px; height: 250px;" src="<?= $article['image']; ?>" data-holder-rendered="true">
         </div>
    </div>
    
    <?php endforeach; ?>
