<!DOCTYPE html>
<html lang="en">
	<head>
	  <title>MyBlog</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
	  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	  <link rel="stylesheet" href="css/common-v2.css" type="text/css" />
	</head>
	<body>
		
		 <header>
		 	<nav class="navbar navbar-expand-lg navbar-light ">
			  <a class="navbar-brand" href="#">Myblog</a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			
			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item active">
			        <a class="nav-link" href="home.php">Home <span class="sr-only">(current)</span></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="authentification.php">Connexion</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="admin.php">Gerer</a>
			      </li>
			      

			    </ul>
			    <form class="form-inline my-2 my-lg-0">
			      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			      <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
			    </form>
			  </div>
			</nav>
		
		</header>
		
		<main>
		
		<?php	include $template;	?>
			
		</main>
		
		<footer class="mainfooter" role="contentinfo">
			  <div class="footer-middle">
			  <div class="container">
			    <div class="row">
			      <div class="col-md-3 col-sm-6">
			        <!--Column1-->
			        <div class="footer-pad">
			          <h4>Heading 1</h4>
			          <ul class="list-unstyled">
			            <li><a href="#"></a></li>
			            <li><a href="#">Payment Center</a></li>
			            <li><a href="#">Contact Directory</a></li>
			            <li><a href="#">Forms</a></li>
			            <li><a href="#">News and Updates</a></li>
			            <li><a href="#">FAQs</a></li>
			          </ul>
			        </div>
			      </div>
			      <div class="col-md-3 col-sm-6">
			        <!--Column1-->
			        <div class="footer-pad">
			          <h4>Heading 2</h4>
			          <ul class="list-unstyled">
			            <li><a href="#">Website Tutorial</a></li>
			            <li><a href="#">Accessibility</a></li>
			            <li><a href="#">Disclaimer</a></li>
			            <li><a href="#">Privacy Policy</a></li>
			            <li><a href="#">FAQs</a></li>
			            <li><a href="#">Webmaster</a></li>
			          </ul>
			        </div>
			      </div>
			      <div class="col-md-3 col-sm-6">
			        <!--Column1-->
			        <div class="footer-pad">
			          <h4>Heading 3</h4>
			          <ul class="list-unstyled">
			            <li><a href="#">Parks and Recreation</a></li>
			            <li><a href="#">Public Works</a></li>
			            <li><a href="#">Police Department</a></li>
			            <li><a href="#">Fire</a></li>
			            <li><a href="#">Mayor and City Council</a></li>
			            <li>
			              <a href="#"></a>
			            </li>
			          </ul>
			        </div>
			      </div>
			    	<div class="col-md-3">
			    		<h4>Follow Us</h4>
			            <ul class="social-network social-circle">
			             <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
			             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
			            </ul>				
					</div>
			    </div>
				<div class="row">
					<div class="col-md-12 copy">
						<p class="text-center">&copy; Copyright 2018 - Company Name.  All rights reserved.</p>
					</div>
				</div>
			
			
			  </div>
			  </div>
		</footer>
	  
	  
	</body>
</html>